---
permalink: linux-administration/concept_what_the_web_service_and_daemon_are.html 
sidebar: sidebar 
keywords: snap, snapdrive, web, service, daemon, interface, snapmanager, cli, command 
summary: 'Le service Web SnapDrive pour UNIX offre une interface uniforme pour tous les produits NetApp SnapManager et tiers afin de s"intégrer en toute transparence à SnapDrive pour UNIX. Pour utiliser les commandes de l"interface de ligne de commande \(CLI\) dans SnapDrive pour UNIX, vous devez démarrer le démon.' 
---
= Ce que sont le service Web et le démon
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le service Web SnapDrive pour UNIX offre une interface uniforme pour tous les produits NetApp SnapManager et tiers afin de s'intégrer en toute transparence à SnapDrive pour UNIX. Pour utiliser les commandes de l'interface de ligne de commande dans SnapDrive pour UNIX, vous devez démarrer le démon.

Divers produits NetApp SnapManager utilisent l'interface de ligne de commande pour communiquer avec SnapDrive pour UNIX. L'utilisation de l'interface de ligne de commande impose une contrainte sur les performances et la gestion de SnapManager et SnapDrive pour UNIX. Lorsque vous utilisez le démon SnapDrive pour UNIX, toutes les commandes fonctionnent comme un processus unique. Le service démon n'affecte pas la façon dont les commandes SnapDrive pour UNIX sont utilisées.

Le service Web SnapDrive pour UNIX permet aux applications tierces de s'intégrer de façon transparente à SnapDrive pour UNIX. Ils interagissent avec SnapDrive pour UNIX à l'aide d'API.

Lorsque vous démarrez le démon, SnapDrive for UNIX Daemon vérifie d'abord si ce dernier est en cours d'exécution. Si le démon n'est pas en cours d'exécution, il démarre le démon. Si le démon est déjà en cours d'exécution et que vous essayez de le démarrer, SnapDrive pour UNIX affiche le message suivant :

`snapdrive daemon is already running`

Vous pouvez vérifier l'état du démon pour savoir si SnapDrive pour UNIX est en cours d'exécution ou non. Vous devez vérifier l'état avant de décider de démarrer le démon. Si un utilisateur autre que l'utilisateur root tente de vérifier l'état, SnapDrive for UNIX vérifie les informations d'identification de l'utilisateur et affiche le message :

`snapdrive daemon status can be seen only by root user`

Lorsque vous essayez d'arrêter le démon, SnapDrive for UNIX vérifie vos informations d'identification. Si vous êtes un utilisateur autre que l'utilisateur root, SnapDrive pour UNIX affiche le message

`snapdrive daemon can be stopped only by root user`

Après avoir arrêté le démon, vous devez redémarrer le démon SnapDrive pour UNIX pour que les modifications apportées au fichier de configuration ou à tout module soient appliquées. Si un utilisateur autre que l'utilisateur root tente de redémarrer le démon SnapDrive for UNIX, SnapDrive for UNIX vérifie les informations d'identification de l'utilisateur et affiche le message

`snapdrive daemon can be restarted only by root user`
