---
permalink: linux-administration/concept_supported_partition_devices.html 
sidebar: sidebar 
keywords: snap, snapdrive, support, storage, partitioning, multipathing 
summary: SnapDrive pour UNIX 5.0 ou version ultérieure assure le partitionnement du stockage sous Linux pour les environnements multipathing et non multipathing. 
---
= Périphériques de partition pris en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive pour UNIX 5.0 ou version ultérieure assure le partitionnement du stockage sous Linux pour les environnements multipathing et non multipathing.

Vous devez suivre les instructions pour partitionner les périphériques de stockage avec SnapDrive pour UNIX.

Lorsque vous utilisez Logical Volume Manager sous Linux, vous devez utiliser des LUN non partitionnées.

Les tableaux suivants fournissent des informations sur les partitions et leur activation pour différents systèmes d'exploitation :

|===
| Système d'exploitation | Partition unique | Partition multiple | Périphériques sans partition | Système de fichiers ou périphériques RAW 


 a| 
Red Hat Enterprise Linux 5x

ou

Oracle Enterprise Linux 5 fois
 a| 
Oui.
 a| 
Non
 a| 
Non
 a| 
ext3*



 a| 
Red Hat Enterprise Linux 6x

ou

Oracle Enterprise Linux 6x
 a| 
Oui.
 a| 
Non
 a| 
Non
 a| 
ext3 ou ext4*



 a| 
SUSE Linux Enterprise Server 11
 a| 
Oui.
 a| 
Non
 a| 
Non
 a| 
ext3*



 a| 
SUSE Linux Enterprise Server 10
 a| 
Non
 a| 
Non
 a| 
Oui.
 a| 
ext3***



 a| 
Red Hat Enterprise Linux 5x ou version ultérieure

ou

Oracle Enterprise Linux 5x ou version ultérieure
 a| 
Oui.
 a| 
Non
 a| 
Oui.
 a| 
ASM avec ASMlib**



 a| 
SUSE Linux Enterprise Server 10 SP4

ou

SUSE Linux Enterprise Server 11
 a| 
Oui.
 a| 
Non
 a| 
Oui.
 a| 
ASM avec ASMlib**



 a| 
SUSE Linux Enterprise Server 10 SP4 ou version ultérieure

ou

SUSE Linux Enterprise Server 11
 a| 
Oui.
 a| 
Non
 a| 
Non
 a| 
ASM sans ASMlib****



 a| 
*

Pour un environnement non MPIO, saisissez la commande suivante : `*sfdisk -uS -f -L -q /dev/ _device_name_*`

Pour un environnement MPIO, entrez les commandes suivantes :

* `*sfdisk -uS -f -L -q /dev/ _device_name_*`
* `*kpartx -a -p p /dev/mapper/ _device_name_*`




 a| 
**

Pour un environnement non MPIO, saisissez la commande suivante :
`*fdisk /dev/_device_name_*`

Pour un environnement MPIO, entrez les commandes suivantes :

* `*fdisk /dev/mapper/_device_name_*`
* `*kpartx -a -p p /dev/mapper/_device_name_*`




 a| 
\***

Sans objet



 a| 
\****

Pour un environnement MPIO, entrez la commande suivante :

* `*kpartx -a -p p /dev/$kernel*`


|===
*Considérations générales*

Les copies Snapshot créées dans SnapDrive pour UNIX 4.2 sont basées sur des périphériques partitionnés. Ces copies Snapshot peuvent être restaurées, connectées et prises en charge dans SnapDrive pour UNIX 5.0 et versions ultérieures.
