---
permalink: linux-administration/concept_guidelines_for_usingthe_storage_deletecommand.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, delete, command, guidelines, file 
summary: La commande SnapDrive Storage delete comporte des restrictions dans SnapDrive for UNIX. 
---
= Instructions d'utilisation de la commande Storage delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `snapdrive storage delete` La commande comporte des restrictions dans SnapDrive pour UNIX.

* Lorsque vous supprimez un système de fichiers, SnapDrive pour UNIX supprime toujours le point de montage du système de fichiers.
+
Les hôtes Linux vous permettent d'attacher plusieurs systèmes de fichiers à un seul point de montage. Cependant, SnapDrive pour UNIX nécessite un point de montage unique pour chaque système de fichiers. Le `snapdrive storage delete` la commande échoue si vous l'utilisez pour supprimer des systèmes de fichiers attachés à un point de montage unique.

* Si vous utilisez le `-lun` Option permettant de spécifier le nom d'une LUN membre d'un groupe de disques hôtes ou d'un système de fichiers, le `snapdrive storage delete` échec de la commande.
* Si vous utilisez `-lun` Option permettant de spécifier le nom de la LUN qui n'est pas détecté par le logiciel de chemins d'accès multiples sur l'hôte, le `snapdrive storage delete` échec de la commande.



NOTE: `snapdrive storage delete` La commande échoue lors de l'utilisation de la LUN RDM, si le groupe initiateur de mappage comporte plus de deux WWPN (World Wide Port Name) dans les versions antérieures à SnapDrive 5.2 pour UNIX.
