---
permalink: linux-administration/concept_restoring_snapshotcopies_ona_destination_storagesystem.html 
sidebar: sidebar 
keywords: snap, snapdrive, restore, storage, system, snapshot, copy 
summary: Vous pouvez restaurer des copies Snapshot sur le système de stockage à partir duquel elles sont créées. 
---
= Restauration de copies Snapshot sur un système de stockage de destination
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer des copies Snapshot sur le système de stockage à partir duquel elles sont créées.

Lorsque vous créez une copie Snapshot sur un système de stockage cible, la copie Snapshot est automatiquement répliquée depuis le système source, où elle est créée dans le système de stockage de destination. SnapDrive pour UNIX vous permet de restaurer la copie Snapshot sur le système de stockage source. La copie Snapshot peut également être restaurée sur le système de stockage de destination.

Si vous effectuez une restauration Snapshot de fichier unique dans une relation SnapMirror, les noms des volumes source et de destination ne doivent pas être identiques. SnapDrive pour UNIX affiche le message d'erreur suivant si les noms des volumes source et de destination sont identiques :

[listing]
----
0001-636 Command error: Snapdrive cannot restore LUNs on SnapMirror
destination filer volumes: <filer-vol-name>
----
Dans SnapDrive 4.0 pour UNIX et les versions ultérieures, si le contrôle d'accès basé sur des rôles est activé, vous pouvez effectuer une restauration Snapshot sur l'unité vFiler uniquement lorsque la fonctionnalité de restauration Snapshot est activée sur l'unité vFiler.

*Informations connexes*

xref:concept_role_based_access_control_in_snapdrive_for_unix.adoc[Contrôle d'accès basé sur des rôles dans SnapDrive pour UNIX]
