---
permalink: linux-administration/reference_snapshot_operation_command_lines.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, command, unix 
summary: Les commandes SnapDrive pour UNIX sont utilisées pour les opérations Snapshot. 
---
= Lignes de commande des opérations de snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les commandes SnapDrive pour UNIX sont utilisées pour les opérations Snapshot.

Le tableau suivant présente diverses options de ligne de commande pour les opérations Snapshot.

|===
| Fonctionnement | Options de ligne de commande 


 a| 
Création
 a| 
`snapdrive snap create [-lun | -dg | -vg | -hostvol | -lvol | -fs] _file_spec_ [file_spec ...] [{-lun | -dg | -vg | -hostvol | -lvol | -fs} _file_spec_ [file_spec ...] ...] -snapname _snap_name_ [-force [-noprompt]] [-unrelated] [-fstype type] [-vmtype type]`



 a| 
Afficher/liste
 a| 
`snapdrive snap { show | list } -filervol _filervol_ [_filervol..._][-verbose]`



 a| 
`snapdrive snap { show | list } [-verbose] {-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [file_spec...] [-fstype type] [-vmtype type]`



 a| 
`snapdrive snap [-verbose] [-snapname] _long_snap_name_ [snap_name ...]`



 a| 
`snapdrive snap {show |list} [-verbose] [-lun | -vg | -dg | -fs | -lvol | -hostvol] _file_spec_ [file_spec...]`



 a| 
Connectez-vous
 a| 
`snapdrive snap connect -lun _s_lun_named_lun_name_ [[-lun] _s_lun_named_lun_name ..._] -snapname _long_snap_name_ [-split] [-clone {lunclone | optimal | unrestricted}] [-prefixfvprefixstr] [-verbose]`


NOTE: Dans une commande SnapDrive snap Connect, le nom de LUN doit être au format `lun_name` ou `qtree_name/lun_name`.



 a| 
`snapdrive snap connect _fspec_set_ [_fspec_set..._] -snapname _long_snap_name_ [-autoexpand] [-autorename] [-nopersist] [-mntopts options] [{-reserve | -noreserve}] [-readonly] [-split] [-clone {lunclone | optimal | unrestricted}] [-prefixfv prefixstr] [-verbose]`

[NOTE]
====
L'argument fspec_set a le format suivant :

`[-vg | -dg | -fs | -lvol | -hostvol] _src_file_spec_[_dest_file_spec_] [{-destdg | -destvg} dgname] [{-destlv | -desthv} lvname]`

====


 a| 
Renommer
 a| 
`snapdrive snap rename -[snapname ]_old_long_snap_name new_snap_name_ [-force [-noprompt]]`



 a| 
Restaurer
 a| 
`snapdrive snap restore [-lun | -dg | -vg | -hostvol | -lvol | -fs | -file] _file_spec_ [file_spec ...] [{-lun | -dg | -vg | -hostvol | -lvol | -fs | -file} _file_spec_ [file_spec ...] ...] -snapname _snap_name_ [-force [-noprompt]] [-mntopts options][{-reserve | -noreserve}] [-vbsr [preview|execute]]`



 a| 
Déconnexion
 a| 
`snapdrive snap disconnect -lun _long_lun_name_ [_lun_name..._] [-fstype type] [-vmtype type][-split]`



 a| 
`snapdrive snap disconnect {-dg | -vg | -hostvol | -lvol | -fs} _file_spec_ [file_spec ...] [{-dg | -vg | -hostvol | -lvol | -fs} _file_spec_ [file_spec ...] ...] [-full] [-fstype type] [-vmtype type] [-split]`



 a| 
Supprimer
 a| 
`snapdrive snap delete [-snapname] _long_snap_name_ [_snap_name..._][-verbose] [-force [-noprompt]]`

|===