---
permalink: linux-administration/task_changing_asnapshot_copyname.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, rename, command, source, name 
summary: 'Vous pouvez modifier le nom d"une copie Snapshot en utilisant la commande SnapDrive snap rename. L"opération de renommage Snapshot modifie le nom de la copie Snapshot source dans le nom spécifié par l"argument cible.' 
---
= Modification du nom d'une copie Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour modifier le nom d'une copie Snapshot, utilisez la `snapdrive snap rename` commande. L'opération de renommage Snapshot modifie le nom de la copie Snapshot source dans le nom spécifié par l'argument cible.

Avant d'exécuter cette syntaxe, vous devez comprendre les options, mots-clés et arguments mentionnés dans cette commande.

.Étapes
. Entrez la commande suivante pour modifier le nom de la copie Snapshot :
+
`*snapdrive snap rename [-snapname] _old_long_snap_name new_snap_name_ [-force [-noprompt]]*`



Voici quelques exemples de `snapdrive snap rename` commande. La première ligne de commande inclut le `-force` Option, car une copie Snapshot nommée `new snapshot` la copie existe déjà. Dans le second exemple, les deux noms de copie Snapshot utilisent la forme longue du nom, mais ils résolvent les deux sur le même volume de système de stockage.

[listing]
----
snapdrive snap rename -force filer1:/vol/vol1:oldsnap new snapshot
----
[listing]
----
snapdrive snap rename filer1:/vol/vol1:FridaySnap filer1:/vol/vol1:Snap040130
----