---
permalink: linux-administration/task_configuring_management_and_data_interfaces_for_a_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, management, configure, data, interface, nfs, traffic 
summary: Vous pouvez configurer plusieurs interfaces de données pour une seule interface de gestion dans un environnement NFS, de sorte à séparer le trafic de gestion du trafic de données sur votre système de stockage. 
---
= Configuration des interfaces de gestion et de données pour un système de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer plusieurs interfaces de données pour une seule interface de gestion dans un environnement NFS, de sorte à séparer le trafic de gestion du trafic de données sur votre système de stockage.

.Étapes
. Définir la configuration de la nouvelle interface de gestion :
+
`*snapdrive config set root*`

+
[listing]
----
# snapdrive config set root f3050-197-91
Password for root:
Retype password:
----
+
Voici un exemple pour une machine virtuelle de stockage (SVM, anciennement appelée Vserver).

+
[listing]
----
# snapdrive config set vsadmin clstr-vs2
Password for vsadmin:
Retype password:
----
. Configurer l'interface de données pour la nouvelle interface de gestion :
+
`*snapdrive config set*`

+
[listing]
----
# snapdrive config set -mgmtpath f3050-197-91 f3050-220-91#
----
+
Dans la commande précédente, `f3050-197-191` est l'interface de gestion et `f3050-220-91` est l'interface de données.

+
Voici un exemple de SVM.

+
[listing]
----
snapdrive config set -mgmtpath clstr-vs2  clstr-vs2-2
system name   management interface   datapath interface
-------------------------------------------------------
clstr-vs2     10.72.220.203          10.72.221.155
----
+
Dans la sortie, `10.72.220.203` est l'interface de gestion et `10.72.221.155` est l'interface de données.


