---
permalink: linux-administration/task_connecting_to_asnapshot_copy_thatcontains_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, lun, connect, command 
summary: 'Vous pouvez vous connecter à une copie Snapshot qui contient des LUN à l"aide de la commande SnapDrive snap Connect.' 
---
= Connexion à une copie Snapshot qui contient des LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez vous connecter à une copie Snapshot qui contient des LUN à l'aide de `snapdrive snap connect` commande.

.Étapes
. Entrez la syntaxe suivante pour vous connecter à une copie Snapshot qui contient des LUN :
+
`*snapdrive snap connect -lun _s_lun_named_lun_name_ [[-lun] _s_lun_named_lun_name..._ -snapname _long_snap_name_ [-igroup _ig_name_ [_ig_name..._]] [-split]*``

+

NOTE: Le `_s_lun_name_` et `_d_lun_name_` doit être au format lun_name ou qtree_name/lun_name.



Les clones SnapDrive pour UNIX sont les LUN que vous spécifiez et les connectent à un nouvel emplacement.

L'exemple suivant connecte la LUN myLUN1, dans hornet/vol/vol1/tuesdasnapshot à mylun1copy :

[listing]
----
# ./snapdrive snap connect -lun mylun1 mylun1copy -snapname
hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1) mapping new lun(s) ... done
discovering new lun(s) ... done
----
L'exemple suivant illustre la connexion de deux LUN, myLUN1 et myLUN2, et à mylun1copy et mylun2copy, respectivement :

[listing]
----
# ./snapdrive snap connect -lun mylun1 mylun1copy -lun mylun2
mylun2copy -snapname hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1)
mapping new lun(s) ... done
connecting hornet:/vol/vol1/mylun2:
LUN copy mylun2copy ... created
(original: hornet:/vol/vol1/mylun2)
mapping new lun(s) ... done
discovering new lun(s) ... done
----
L'exemple suivant connecte la LUN LUN1_0 à snapshot lech:/vol/vol1:rrt :

[listing]
----

snapdrive snap connect -fs /mnt/fs /mnt/fs1  -snapname lech:/vol/vol1:rrt
connecting /mnt/fs:
   LUN copy lun1_0 ... created
     (original: lech:/vol/vol1/lun1)
   exporting new lun(s) to Guest OS ... done
   discovering new lun(s) ... done
Successfully connected to snapshot lech:/vol/vol1:rrt
        file system: /mnt/fs1
----