---
permalink: aix/concept_example_of_an_autosupport_message.html 
sidebar: sidebar 
keywords: snap, snapdrive, example, autosupport, message, support 
summary: 'SnapDrive pour UNIX fournit des exemples de scénarios différents. Dans tous les exemples, le contenu d"un message AutoSupport est essentiellement le même, quel que soit votre système d"exploitation.' 
---
= Exemples de messages AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive pour UNIX fournit des exemples de scénarios différents. Dans tous les exemples, le contenu d'un message AutoSupport est essentiellement le même, quel que soit votre système d'exploitation.

Exemple : ajout d'un nouveau système de stockage

L'exemple suivant est un message envoyé à partir d'un hôte nommé `_aix207-116_`:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="ohio configured"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
Exemple : redémarrage du démon

SnapDrive pour UNIX envoie le message AutoSupport suivant au système de stockage lorsque vous redémarrez le démon :

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
Lorsqu'une opération de connexion au stockage échoue, SnapDrive for UNIX envoie le message AutoSupport suivant au système de stockage :

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="4"
        category="storage connect failed"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp,1384: LUN /vol/vol0/test1 on storage system ohio already mapped to initiators in igroup aix207-116_fcp_SdIg at ID 0."/
----
SnapDrive pour UNIX envoie le message AutoSupport suivant au système de stockage lorsqu'une `snap create` opération réussie :

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="5"
        category="snap create successful"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp, snapshot_name=snap1"
----