---
permalink: aix/reference_informationrequired_forusing_the_snapdrive_storagedisconnect_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, disconnect, command, required 
summary: 'Le tableau suivant fournit les informations nécessaires à l"alimentation lorsque vous utilisez la commande SnapDrive Storage déconnecter.' 
---
= Informations requises pour l'utilisation de la commande SnapDrive Storage déconnecter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le tableau suivant fournit les informations que vous devez fournir lorsque vous utilisez le `snapdrive storage disconnect` commande :

|===
| Conditions requises | Argument 


 a| 
En fonction de la commande que vous entrez, vous pouvez supprimer les mappages de l'un des types suivants :

* LUN
+
Si vous déconnectez une ou plusieurs LUN, le premier argument doit utiliser la forme longue du nom de la LUN, qui spécifie le nom du système de stockage, le nom du volume et le nom de la LUN dans le volume.

+
Pour spécifier des LUN supplémentaires, vous pouvez utiliser le nom de cette LUN seul si la nouvelle LUN se trouve sur le même système de stockage et sur le même volume que la LUN précédente. Sinon, vous pouvez spécifier un nouveau nom de système de stockage et un nouveau nom de volume (ou simplement un nom de volume) pour remplacer les valeurs précédentes.

* Systèmes de fichiers sur des LUN
+
Le `_file_spec_` remis à `-fs` est le nom du point de montage du système de fichiers. SnapDrive pour UNIX localise et déconnecte automatiquement le LUN associé au système de fichiers que vous spécifiez.

* Groupes de disques ou de volumes
* Systèmes de fichiers sur disques ou groupes de volumes
* Hôte ou volumes logiques


La valeur que vous entrez pour l'argument file_spec doit identifier l'entité de stockage que vous déconnectez.



 a| 
UNE LUN (`-lun`)
 a| 
`_lun_name_` (forme longue ou courte)



 a| 
Groupe de disques (`-dg _file_spec_`) ou groupe de volumes (`-vg _file_spec_`)
 a| 
nom du disque ou groupe de volumes



 a| 
Système de fichiers (`-fs _file_spec_`)
 a| 
`_filesystem_name_`



 a| 
Volume de l'hôte (`-hostvol _file_spec_`) ou volume logique (`-lvol _file_spec_`)
 a| 
nom de l'hôte ou du volume logique



 a| 
Si vous souhaitez que SnapDrive pour UNIX déconnecte le stockage que vous spécifiez, même si vous incluez à l'invite de commande une entité côté hôte qui possède d'autres entités (par exemple un groupe de disques possédant un ou plusieurs volumes hôtes), incluez le `-full` à l'invite de commande.

Si vous n'incluez pas cette option, vous devez spécifier uniquement des entités côté hôte vides.



 a| 
`-full`
 a| 
~



 a| 
Pour désactiver le partage d'un système de fichiers sur un nœud ou un cluster hôte



 a| 
`-fstype`
 a| 
`_type_`



 a| 
`-vmtype`
 a| 
`_type_`



 a| 
*Facultatif:* Spécifie le type de système de fichiers et de gestionnaire de volumes à utiliser pour les opérations SnapDrive pour UNIX.

|===