---
permalink: aix/task_creating_a_filesystem_on_a_lunand_setting_up_thelun_automatically.html 
sidebar: sidebar 
keywords: snap, snapdrive, lun, file, system, create 
summary: 'Vous pouvez créer un système de fichiers sur une LUN à l"aide de SnapDrive pour UNIX. SnapDrive for UNIX crée automatiquement la LUN associée.' 
---
= Création d'un système de fichiers sur une LUN et configuration automatique de celle-ci
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un système de fichiers sur une LUN à l'aide de SnapDrive pour UNIX. SnapDrive for UNIX crée automatiquement la LUN associée.

.Étapes
. En ligne de commande, entrez la commande suivante :
+
`*snapdrive storage create -fs _file_spec_ -nolvm [-fstype type] [-fsopts options] [-mntopts options] [-nopersist] -filervol _long_filer_path_ -lunsize _size_ [-igroup _ig_name [ig_name ...]]_ [{-reserve | -noreserve }]*`

+
SnapDrive for UNIX crée le système de fichiers que vous spécifiez et crée une LUN pour celui-ci sur le système de stockage que vous spécifiez. Il effectue toutes les tâches associées à la préparation et à la découverte des hôtes pour les LUN, ainsi que le mappage et la connexion des LUN à l'entité hôte.





== Exemples :

*Création d'un système de fichiers de 100 Mo directement sur un LUN:*

[listing]
----
# snapdrive storage create -fs /mnt/acct1 -filervol acctfiler:/vol/vol1 -lunsize 100m -nolvm
----
*Création d'un système de fichiers sur une LUN brute sans gestionnaire de volumes :*

[listing]
----
# snapdrive storage create -fs /mnt/vxfs2 -fstype vxfs -lun
snoopy:/vol/vol1/lunVxvm2 -lunsize 50m -nolvm
LUN snoopy:/vol/vol1/lunVxvm2 ... created
mapping new lun(s) ... done
discovering new lun(s) ... done
LUN to device file mappings:
- snoopy:/vol/vol1/lunVxvm2 => /dev/vx/dmp/Disk_1
file system /mnt/vxfs2 created
----