---
permalink: aix/task_estimating_the_storage_space_to_split_a_lun_clone.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, space, split, lun, clone 
summary: 'L"estimation du fractionnement du clone vous aide à estimer l"espace de stockage requis \(en Mo\) pour séparer un clone de LUN. En fonction de l"estimation de séparation des clones fournie par SnapDrive pour UNIX, vous pouvez déterminer l"espace disponible pour séparer un clone de LUN.' 
---
= Estimation de l'espace de stockage pour séparer un clone de LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'estimation du fractionnement des clones permet d'estimer l'espace de stockage requis (en Mo) pour séparer un clone de LUN. En fonction de l'estimation de séparation des clones fournie par SnapDrive pour UNIX, vous pouvez déterminer l'espace disponible pour séparer un clone de LUN.

.Étapes
. Entrez la commande suivante pour estimer l'espace de stockage requis pour séparer un clone de LUN.
+
`*snapdrive clone split estimate [-lun]_long_lun_name_ [_long_lun_name_...] | [{-dg | -vg | -fs | -hostvol | -lvol}__file_spec__ [_file_spec_...]] | [-snapname _long_snap_name_] {-volclone|-lunclone}] [-v | -verbose]*`

+
Cette opération affiche les informations suivantes :

+
** Nom de la ressource
** Container- Volume pour un clone de LUN
** Espace requis : espace requis pour séparer un clone de LUN
** Espace disponible - espace disponible sur le conteneur
** Storage Status : indique la disponibilité de l'espace pour un groupe de clones de LUN
** Owned Space : espace occupé par le clone de LUN
** Shared Space : espace occupé par le clone de LUN et le parent


+
Le `Owned Space` et `Shared Space` s'affiche lorsque vous utilisez `-verbose` option.



L'exemple suivant estime l'espace de stockage permettant de séparer un clone de LUN.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1
Resource     Container Required Available Storage
                       Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  5120    9986    AVAILABLE
             -112:/vol/vol_1
----
Voici un exemple d'utilisation du `-verbose` option. Vous pouvez également utiliser `-v` option.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -verbose
Resource    Container  Owned    Shared   Required Available Storage
                       Space(MB)Space(MB)Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  365   403      5120     9986 AVAILABLE
             -112:/vol/vol_1
----