---
permalink: solaris/concept_guidelines_for_the_storage_resize_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, resize, command 
summary: Suivez quelques instructions lorsque vous utilisez la commande SnapDrive Storage resize. 
---
= Instructions relatives à la commande de redimensionnement du stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous utilisez le, vous devez suivre quelques consignes `snapdrive storage resize` commande.

* Le redimensionnement du stockage ne peut augmenter que la taille du stockage. Vous ne pouvez pas l'utiliser pour réduire la taille d'une entité.
* Toutes les LUN doivent résider dans le même volume de système de stockage.
* L'opération de redimensionnement ne prend pas en charge directement les volumes d'hôtes logiques, ni les systèmes de fichiers qui résident sur des volumes d'hôtes logiques ou sur des LUN. Dans ce cas, vous devez utiliser les commandes LVM pour redimensionner le stockage.
* Vous ne pouvez pas redimensionner une LUN ; vous devez utiliser `-addlun` Option pour ajouter une LUN.
* Le `snapdrive storage resize` on peut exécuter la commande depuis n'importe quel nœud du cluster.
* Le `snapdrive storage resize` la commande ne prend pas en charge le `-devicetype` option.

