---
permalink: solaris/concept_limitations_of_luns_managed_by_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, limitations, lun 
summary: Lorsque vous travaillez avec SnapDrive, vous devez connaître les limites associées aux LUN. 
---
= Limitations des LUN gérées par SnapDrive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous travaillez avec SnapDrive, vous devez connaître les limites associées aux LUN.

* Une LUN gérée par SnapDrive ne peut pas servir de disque de démarrage ou de disque système.
* Les hôtes Solaris ont des limites de système d'exploitation sur le nombre de LUN que vous pouvez créer.
+
Vous pouvez exécuter le `snapdrive config check luns` Commande lorsque vous créez les LUN sur ces hôtes. Cette commande vous permet de déterminer le nombre de LUN que vous pouvez créer.

* SnapDrive ne prend pas en charge les deux-points (:) sous forme de noms de LUN et de copies Snapshot.
+
Les deux-points sont autorisés entre les composants d'une copie Snapshot longue, ou entre le nom du système de stockage et le nom du volume du système de stockage d'une LUN. Par exemple : `toaster:/vol/vol1:snap1` Est un nom de snapshot long typique, pendant `toaster:/vol/vol1/lunA` Est un nom de LUN longue standard.


