---
permalink: solaris/concept_storage_provisioning_for_rdm_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, vmware, vmotion, support, unix 
summary: 'SnapDrive pour UNIX vous permet de vous déconnecter et de connecter les LUN RDM avant et après VMware VMotion. Une fois l"opération VMotion terminée, vous pouvez exécuter les opérations de stockage requises pour votre système de stockage.' 
---
= Prise en charge de VMware VMotion dans SnapDrive for UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive pour UNIX vous permet de vous déconnecter et de connecter les LUN RDM avant et après VMware VMotion. Une fois l'opération VMotion terminée, vous pouvez exécuter les opérations de stockage requises pour votre système de stockage.

*À propos de VMware VMotion:*

VMware VMotion vous permet de déplacer un système invité d'un serveur ESX vers un autre serveur ESX.

Les opérations suivantes doivent être exécutées pour déconnecter et connecter les LUN RDM dans SnapDrive for UNIX.

*Avant VMotion*

Vous devez utiliser le `snapdrive storage disconnect` Commande permettant de supprimer les mappages des LUN RDM. La syntaxe suivante :

`*snapdrive storage disconnect -lun _long_lun_name_ [_lun_name..._]*`

*Après VMotion*

Une fois VMotion terminé, vous devez utiliser le `snapdrive storage connect` Commande pour connecter les LUN RDM. La syntaxe suivante :

`*snapdrive storage connect -lun _long_lun_name_ [_lun_name..._]*`

*Informations connexes*

xref:concept_limitations_of_rdm_luns_managed_by_snapdrive.adoc[Limitations des LUN RDM gérés par SnapDrive]

xref:task_configuring_virtual_storage_console_in_snapdrive_for_unix.adoc[Configuration de Virtual Storage Console pour SnapDrive pour UNIX]

xref:concept_guest_os_preparation_for_installing_sdu.adoc[Préparation du système d'exploitation invité pour l'installation de SnapDrive pour UNIX]

xref:task_considerations_for_provisioning_rdm_luns.adoc[Considérations relatives au provisionnement des LUN RDM]
