---
permalink: solaris/concept_operation_with_multiple_storage_objects.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, object, multiple, error 
summary: 'L"exemple suivant montre le message d"erreur que vous recevrez lorsque vous n"êtes pas un utilisateur autorisé à effectuer l"opération spécifique.' 
---
= Fonctionnement avec plusieurs objets de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'exemple suivant montre le message d'erreur que vous recevrez lorsque vous n'êtes pas un utilisateur autorisé à effectuer l'opération spécifique.

[listing]
----
[john]$ snapdrive storage show –all

Connected LUNs and devices:

device filename   adapter  path  size  proto  state  clone  lun path                           backing Snapshot
----------------  -------  ----  ----  -----  -----  -----  --------                           ---------------
/dev/sdao            -     -     200m  iscsi  online  No    storage_array1:/vol/vol2/passlun1           -
/dev/sda1            -     -     200m  fcp    online  No    storage_array1:/vol/vol2/passlun2           -

Host devices and file systems:

dg: testfs1_SdDg                dgtype lvm
hostvol: /dev/mapper/testfs1_SdDg-testfs1_SdHv  state: AVAIL
fs: /dev/mapper/testfs1_SdDg-testfs1_SdHv       mount point: /mnt/testfs1 (persistent) fstype ufs

device filename   adapter  path  size  proto  state   clone  lun path                                backing Snapshot
----------------  -------  ----  ----  -----  -----   -----  --------                                ---------
/dev/sdn             -      P    108m  iscsi  online   No    storage_array1:/vol/vol2/testfs1_SdLun         -
/dev/sdn1             -      P    108m  fcp  online   No    storage_array1:/vol/vol2/testfs1_SdLun1         -

0002-719 Warning: SD.Storage.Read access denied on volume storage_array1:/vol/vol1 for user unix_host\john on Operations Manager server ops_mngr_server
----
John est autorisé à répertorier les entités de stockage sur vol2, mais pas sur vol1. SnapDrive pour UNIX affiche les entités de vol1 et affiche un message d'avertissement pour vol2.


NOTE: Pour `storage list`, `storage show`, `snap list`, et `snap show` Commandes SnapDrive pour UNIX affiche un avertissement au lieu de l'erreur.
