---
permalink: solaris/task_setting_up_an_sfrac_i_o_fencing_environment_on_a_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, sfrac, fencing, environment, storage 
summary: SnapDrive pour UNIX offre des options de provisionnement du stockage et de gestion Snapshot pour gérer des groupes de disques partagés et locaux au niveau du cluster hôte, ainsi que des systèmes de fichiers dans un environnement SFRAC. 
---
= Configuration d'un environnement de clôture d'E/S SFRAC sur un système de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive pour UNIX offre des options de provisionnement du stockage et de gestion Snapshot pour gérer des groupes de disques partagés et locaux au niveau du cluster hôte, ainsi que des systèmes de fichiers dans un environnement SFRAC.

.Étapes
. Configuration `rsh` ou `ssh` manuellement pour utiliser l'invite d'accès sans mot de passe pour l'utilisateur root sur tous les nœuds du cluster hôte.
+
Pour obtenir des instructions de configuration, reportez-vous au _Veritas Cluster Server installation Guide for Solaris_.

. Installez SnapDrive pour UNIX sur tous les nœuds du cluster hôte.
+
Si différentes versions de SnapDrive pour UNIX sont installées sur différents nœuds, les opérations de SnapDrive pour UNIX échouent.

. Vérifier la connectivité FC entre les systèmes de stockage.
+
Pour en savoir plus sur la configuration matérielle requise pour les hôtes, consultez les notes de mise à jour SFRAC _Release_.

+

NOTE: Le `/opt/NTAPsnapdrive/snapdrive.conf` sur tous les nœuds doivent avoir le `default-transport` La variable de configuration est définie sur FCP.

. Définissez une valeur pour le `_secure-communication-among-cluster-nodes_` variable de configuration, pour s'assurer que le `rsh` ou `ssh` access-sans-password-prompt pour l'utilisateur root est configuré pour tous les nœuds du cluster.
+
Cette valeur est nécessaire car, si vous initiez les commandes SnapDrive for UNIX à partir d'un nœud (maître ou non maître) du cluster hôte, SnapDrive for UNIX effectue des opérations sur d'autres nœuds du cluster hôte.

. Vérifiez la détection des périphériques sur les nœuds du cluster hôte en exécutant la commande suivante sur chaque nœud du cluster hôte :
+
`*snapdrive storage create -lun _long_lun_name_ [_lun_name..._] -lunsize size [{_-reserve_ | _-noreserve_}] [_-igroup ig_name_ [_ig_name ..._]]*`

+
[listing]
----

	# snapdrive storage create -lun f270-197-109:/vol/vol2/luntest -lunsize 20m

		LUN f270-197-109:/vol/vol2/luntest ... created

		mapping new lun(s) ... done
		discovering new lun(s) ... done

		LUN to device file mappings:
	-f270-197-109:/vol/vol2/luntest => /dev/vx/dmp/c5t0d6s2

	# snapdrive storage delete -lun f270-197-109:/vol/vol2/luntest -lunsize 20m
	- LUN f270-197-109:/vol/vol2/luntest ... deleted
----

