---
permalink: solaris/task_connecting_tosnapshot_copies_ofshared_storageentities_other_thanluns.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, snapshot, copy, shared, storage, lun 
summary: 'Vous pouvez utiliser la commande SnapDrive snap Connect pour vous connecter à une copie Snapshot d"entités de stockage partagées autres que les LUN.' 
---
= Connexion aux copies Snapshot d'entités de stockage partagées autres que LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `snapdrive snap connect` Commande permettant de se connecter à une copie Snapshot d'entités de stockage partagées autres que LUN.

.Étapes
. Saisissez la commande suivante :
+
`*snapdrive snap connect _fspec_set_ [_fspec_set..._] -snapname _long_snap_name_ [-devicetype shared] [-split]*`

+
Dans cette syntaxe, `_fspec_set_` est : `{-dg | -fs}_src_file_spec_ [_dest_file_spec_ ] [-destdg _dgname_]`



L'exemple suivant se connecte à une copie Snapshot qui contient des entités de stockage partagé sur un cluster hôte d'origine. L'opération est exécutée depuis le nœud non-cluster-master, mais la commande est envoyée au nœud maître et exécutée :

[listing]
----
# snapdrive snap connect -fs /mnt/sfortesting /mnt/sfortesting2 -
snapname f270-
197-109:/vol/vol2:testsfarcsnap -devicetype shared -autorename
Execution started on cluster master: sfrac-57
connecting sfortesting_SdDg:
LUN copy sfortesting_SdLun_0 ... created
(original: f270-197-109:/vol/vol2/sfortesting_SdLun)
mapping new lun(s) ... done
discovering new lun(s) ... done
Connecting cluster node: sfrac-58 mapping lun\(s\) ... done
discovering lun(s) ... done
LUN f270-197-109:/vol/vol2/sfortesting_SdLun_0 connected
- device filename(s): /dev/vx/dmp/c3t0d22s2
Importing sfortesting_SdDg_0
Activating hostvol sfracvxfstestfs_SdHv_0
Successfully connected to snapshot f270-197-
109:/vol/vol2:testsfarcsnap
disk group sfortesting_SdDg_0 containing host volumes
sfortesting_SdHv_0 (filesystem: /mnt/sfortesting2)
----
L'exemple suivant se connecte à une copie Snapshot qui contient des entités de stockage partagées sur un cluster hôte non originaire. L'opération est exécutée depuis le nœud non-cluster-master, mais la commande est envoyée au nœud maître et exécutée :

[listing]
----
# snapdrive snap connect -fs /mnt/sfortesting -snapname f270-197-
109:/vol/vol2:testsfarcsnap -devicetype shared
Execution started on cluster master: sfrac-57
connecting sfortesting_SdDg:
LUN copy sfortesting_SdLun_0 ... created
(original: f270-197-109:/vol/vol2/sfortesting_SdLun)
Step Action
184 Connecting to a Snapshot copy
mapping new lun(s) ... done
discovering new lun(s) ... done
Connecting cluster node: sfrac-58
mapping lun(s) ... done
discovering lun(s) ... done
LUN f270-197-109:/vol/vol2/sfortesting_SdLun_0 connected
- device filename(s): /dev/vx/dmp/c3t0d1s2
Importing sfortesting_SdDg
Activating hostvol sfortesting_SdHv
Successfully connected to snapshot f270-197-
109:/vol/vol2:testsfarcsnap
disk group sfortesting_SdDg containing host volumes
sfortesting_SdHv (filesystem: /mnt/sfortesting)
----