---
permalink: solaris/task_configuring_user_credentials_on_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, configure, user, credential 
summary: 'L"administrateur SnapDrive pour UNIX reçoit les informations d"identification de l"utilisateur de l"administrateur de la console Operations Manager. Ces identifiants utilisateur doivent être configurés sur SnapDrive pour UNIX afin que les opérations de stockage soient correctes.' 
---
= Configuration des informations d'identification utilisateur sous SnapDrive for UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'administrateur SnapDrive pour UNIX reçoit les informations d'identification de l'utilisateur de l'administrateur de la console Operations Manager. Ces identifiants utilisateur doivent être configurés sur SnapDrive pour UNIX afin que les opérations de stockage soient correctes.

.Étapes
. Configurez sd-admin sur le système de stockage.
+
[listing]
----
[root]#snapdrive config set -dfm sd-admin ops_mngr_server
Password for sd-admin:
Retype password:
----
. Configurez sd-hostname sur le système de stockage.
+
[listing]
----
[root]#snapdrive config set sd-unix_host storage_array1
Password for sd-unix_host:
Retype password:
----
. Vérifier les étapes 1 et 2 à l'aide du `snapdrive config list` commande.
+
[listing]
----
user name       appliance name          appliance type
----------------------------------------------------
sd-admin        ops_mngr_server         DFM
sd-unix_host    storage_array1          StorageSystem
----
. Configurer SnapDrive pour UNIX afin d'utiliser le contrôle d'accès basé sur des rôles (RBAC) sur la console Operations Manager en définissant la variable de configuration `_rbac-method="dfm"_` dans le `snapdrive.conf` fichier.
+

NOTE: Les informations d'identification de l'utilisateur sont cryptées et enregistrées dans l'existant `.sdupw` fichier. L'emplacement par défaut du fichier précédent est `/opt/ONTAPsnapdrive/.sdupw`.


