---
permalink: solaris/task_estimating_the_storage_space_to_split_a_volume_clone.html 
sidebar: sidebar 
keywords: clone, split, estimate, snap, snapdrive, volume 
summary: 'L"estimation du fractionnement du clone vous aide à estimer l"espace de stockage requis \(en Mo\) pour séparer un clone de volume. En fonction de l"estimation de séparation des clones fournie par SnapDrive pour UNIX, vous pouvez déterminer l"espace disponible pour séparer un clone de volume.' 
---
= Estimation de l'espace de stockage pour séparer un clone de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'estimation du fractionnement du clone vous permet d'estimer l'espace de stockage requis (en Mo) pour séparer un clone de volume. En fonction de l'estimation de séparation des clones fournie par SnapDrive pour UNIX, vous pouvez déterminer l'espace disponible pour séparer un clone de volume.

.Étapes
. Entrez la commande suivante pour estimer l'espace de stockage nécessaire pour séparer un clone de volume.
+
`*snapdrive clone split estimate [-lun] _long_lun_name_ [long___lun_name__...] | [{-dg | -vg | -fs | -hostvol | -lvol} _file_spec_ [_file_spec..._]] | [-snapname _long_snap_name_] {-volclone|-lunclone}] [-v | -verbose] [-dump | -dumpall]*`

+
Cette opération affiche les informations suivantes :

+
** Nom de la ressource
** Container : agrégat pour un FlexClone
** Espace requis : espace requis pour séparer le clone du volume
** Espace disponible - espace disponible sur le conteneur
** Storage Status : indique la disponibilité de l'espace pour un fractionnement de clone de volume
** Owned Space : espace occupé par le clone du volume
** Espace partagé : espace occupé par le clone de volume avec le parent


+
Le `Owned Space` et `Shared Space` s'affiche lorsque vous utilisez `-verbose` option.



L'exemple suivant estime l'espace de stockage nécessaire pour séparer un clone de volume.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -fs /mnt/my_mnt2
Resource     Container  Required Available  Storage
                        Space(MB) Space(MB) Status
/mnt/my_mnt1  f3050-220  400      61500    AVAILABLE
              -111:aggr0
/mnt/my_mnt2  f3050-220  3292     1129     NOT AVAILABLE
              -112:aggr1
----
Pour chaque spécification de fichier, SnapDrive for UNIX détermine l'espace requis disponible dans le système de stockage afin de séparer un clone de volume. Ici, le `/mnt/my_mnt1` La spécification de fichier dispose de l'espace requis pour le fractionnement, et l'état de stockage s'affiche donc comme DISPONIBLE. Attendu que, le `/mnt/my_mnt2` La spécification de fichier ne dispose pas de l'espace requis pour le fractionnement, de sorte que l'état de stockage s'affiche comme NON DISPONIBLE.

Voici un exemple d'utilisation du `-verbose` option. Vous pouvez également utiliser `-v` option.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -verbose
Resource    Container Owned    Shared   Required Available Storage
                      Space(MB)Space(MB)Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220 32365  403      403     55875 AVAILABLE
             -111:aggr0
----